<?php

/**
 *  @file media_oembed/media_oembed.module
 *
 *  Media: oEmbed provides a stream wrapper and formatters for videos provided
 *  by oEmbed, format documented at http://oembed.com/.
 */

/**
 *  Create stream wrapper for oEmbed videos.
 */
function media_oembed_stream_wrappers() {
  return array(
    'oembed' => array(
      'name' => t('oEmbed resources'),
      'class' => 'MediaOEmbedStreamWrapper',
      'description' => t('Resources provided by oEmbed.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_file_formatter_info().
 */
function media_oembed_file_formatter_info() {
  $formatters['media_oembed'] = array(
    'label' => t('oEmbed'),
    'default settings' => array('width' => '560', 'height' => '340'),
    'view callback' => 'media_oembed_file_formatter_media_oembed_view',
    'settings callback' => 'media_oembed_file_formatter_media_oembed_settings',
  );
  $formatters['media_oembed_thumbnail'] = array(
    'label' => t('oEmbed Thumbnail'),
    'default settings' => array('width' => '560', 'height' => '340'),
    'view callback' => 'media_oembed_file_formatter_media_oembed_thumbnail_view',
    'settings callback' => 'media_oembed_file_formatter_media_oembed_thumbnail_settings',
  );
  return $formatters;
}

/**
 * Implements hook_file_default_displays().
 *
 * Provides default display configurations for media types.
 *
 * @see file_entity_schema()
 */
function media_oembed_file_default_displays() {
  $default_displays = array();

  $default_styles = array();
  foreach(media_type_get_types() as $name => $type) {
    // For default and Large view modes, use the default width and height from
    // hook_file_formatter_info().
    $default_styles[$name . '__default__media_oembed'] = array();
    $default_styles[$name . '__default__media_oembed_thumbnail'] = array();
    $default_styles[$name . '__media_large__media_oembed'] = array();
    $default_styles[$name . '__media_large__media_oembed_thumbnail'] = array();

    // For the Preview view mode, match the width and height of the square
    // thumbnail in media_image_default_styles().
    $default_styles[$name . '__media_preview__media_oembed_thumbnail'] = array('width' => '180', 'height' => '180');

    // For the Original view mode, set width and height to empty, so that they
    // use what's returned by the oEmbed response.
    $default_styles[$name . '__media_original__media_oembed'] = array('width' => '', 'height' => '');
    $default_styles[$name . '__media_original__media_oembed_thumbnail'] = array('width' => '', 'height' => '');
  }

  foreach ($default_styles as $display_name => $settings) {
    $default_displays[$display_name] = (object) array(
      'api_version' => 1,
      'name' => $display_name,
      'status' => 1,
      'weight' => 0,
      'settings' => $settings,
    );
  }

  return $default_displays;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_oembed_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}

/**
 * Implements hook_file_formatter_FORMATTER_view().
 */
function media_oembed_file_formatter_media_oembed_view($file, $display, $langcode) {
  $scheme = file_uri_scheme($file->uri);
  if ($scheme == 'oembed') {
    $url = rawurldecode(substr($file->uri, 9));

    // Strict sizing doesn't work reliably.
    $options = array(
      'width' => isset($file->override['width']) ? $file->override['width'] : $display['settings']['width'],
      'height' => isset($file->override['height']) ? $file->override['height'] : $display['settings']['height'],
    );

    // Not a WYSIWYG editor instance.
    if (empty($file->override['wysiwyg'])) {
      $element = oembedcore_render_cache('oembed', $url, $options);
    }

    // WYSIWYG does not yet support video inside a running editor instance, send
    // thumbnails.
    else {
      $element = oembedcore_render_cache('oembed_thumbnail', $url, $options);
      if (!empty($file->override['attributes'])) {
        $element['#options']['attributes'] = $file->override['attributes'];
      }
    }
    return $element;
  }
}

/**
 * Implements hook_file_formatter_FORMATTER_settings().
 */
function media_oembed_file_formatter_media_oembed_settings($form, &$form_state, $settings) {
  $element = array();
  $element['width'] = array(
    '#title' => t('Width'),
    '#type' => 'textfield',
    '#default_value' => $settings['width'],
  );
  $element['height'] = array(
    '#title' => t('Height'),
    '#type' => 'textfield',
    '#default_value' => $settings['height'],
  );
  return $element;
}

/**
 * Implements hook_file_formatter_FORMATTER_view().
 */
function media_oembed_file_formatter_media_oembed_thumbnail_view($file, $display, $langcode) {
  $scheme = file_uri_scheme($file->uri);
  if ($scheme == 'oembed') {
    $wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
    $element = oembedcore_render_cache('oembed_thumbnail', $wrapper->interpolateUrl(), $display['settings']);
    $element['#attributes'] = $display['settings'];
    return $element;
  }
}

/**
 * Implements hook_file_formatter_FORMATTER_settings().
 */
function media_oembed_file_formatter_media_oembed_thumbnail_settings($form, &$form_state, $settings) {
  $element = array();
  $element['width'] = array(
    '#title' => t('Width'),
    '#type' => 'textfield',
    '#default_value' => $settings['width'],
  );
  $element['height'] = array(
    '#title' => t('Height'),
    '#type' => 'textfield',
    '#default_value' => $settings['height'],
  );
  return $element;
}

/**
 *  Implements hook_media_parse().
 *
 *  @todo: this might be deprecated now that we have media_internet,
 *  but the hook is still being called in a couple places in media.
 */
function media_oembed_media_parse($url, $options = array()) {
  $scheme = 'oembed://';
  $matches = array();
  if ($provider = oembedcore_get_provider($url, $matches)) {
    return file_stream_wrapper_uri_normalize($scheme . drupal_encode_path($url));
  }
  // @TODO: Validate for malformed oembed urls.
}

/**
 * Implements hook_media_internet_providers();
 */
function media_oembed_media_internet_providers() {
  $path = drupal_get_path('module', 'media_oembed');
  return array(
    'MediaInternetOEmbedHandler' => array(
      'title' => 'oEmbed',
    ),
  );
}

/**
 * Implements hook_media_operations().
 */
function media_oembed_media_operations() {
  $operations = array(
    'refresh' => array(
      'label' => t('Refresh from source'),
      'callback' => 'media_oembed_cache_clear',
    ),
  );
  return $operations;
}

/**
 * Clear the cached oEmbed content for the selected files.
 */
function media_oembed_cache_clear($fids) {
  $fids = array_keys($fids);

  $query = new EntityFieldQuery();
  $results = $query
    ->entityCondition('entity_type', 'file')
    ->propertyCondition('uri', 'oembed:', 'STARTS_WITH')
    ->propertyCondition('fid', $fids)
    ->execute();

  $files = file_load_multiple(array_keys($results['file']));
  foreach ($files as $file) {
    $wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
    $url = $wrapper->interpolateUrl();
    $hashed_url = hash('sha256', $url);
    foreach (array('oembed', 'oembed_thumbnail') as $type) {
      $cid = $type . ':' . $hashed_url . ':';
      cache_clear_all($cid, 'cache_oembed', TRUE);
    }
  }
}

class MediaInternetOEmbedHandler extends MediaInternetBaseHandler {

  /**
   * Claim this URL.
   */
  public function claim($embedCode) {
    $matches = array();
    if (oembedcore_get_provider($embedCode, $matches)) {
      return TRUE;
    }
  }

  /**
   * Returns a file object which can be used for validation
   *
   * @return StdClass
   */
  public function getFileObject() {
    $uri = 'oembed://'. drupal_encode_path($this->embedCode);
    return file_uri_to_object($uri);
  }

  /**
   * Before the file has been saved, implementors may do additional operations.
   */
  public function preSave(&$file_obj) {
    $url = rawurldecode(substr($file_obj->uri, 9));
    $embed = oembedcore_oembed_data($url);
    if (!empty($embed->title)) {
      $file_obj->filename = $embed->title;
    }
  }
}
